### ISSUE TITLE
Helm Chart not compatible with kustomize from version >1.7.63

### ISSUE THREAD

**Issue by f-helm** [kubeshop/helm-charts#352]
**Describe the bug**
Helm Chart cannot be rendered with kustomize build from helm chart verisons greater than 1.7.63

**To Reproduce**
1. Create kustomization.yaml file, e.g. 
```
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

helmCharts:
- name: testkube
  releaseName: testkube
  repo: https://kubeshop.github.io/helm-charts
```
3. In directory of kustomize.yaml, run `kustomize build . --enable-helm`
5. See error
```
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 12: mapping key "helm.sh/chart" already defined at line 8
  line 13: mapping key "app.kubernetes.io/managed-by" already defined at line 9
```
**Expected behavior**
Build goes through without errors

**Version / Cluster**
- Which testkube version? Helm Chart >1.7.63
- Version:kustomize/v4.5.7
 
**Additional context**
It is likely that labels of testkube-operator are responsible for this behaviour: https://github.com/kubeshop/helm-charts/commit/a399e4ef86d670145b0a79d0aa17599167e8eb75
Add `version: 1.7.63` under `helmCharts:` to verify that this worked correctly in earlier versions.
