### ISSUE TITLE
monitoringLabels do not get set for service monitor

### ISSUE THREAD

**Issue by f-helm** [kubeshop/helm-charts#367]
**Describe the bug**
Custom labels set via testkube chart values can not be found in service monitor

**To Reproduce**
1. Set custom values for testkube chart: 
```
testkube-api:
  prometheus:
    enabled: true
  monitoringLabels:
    - release: "my-release"
```
2. install testkube

**Expected behavior**
Service monitor contains label metadata.labels.release = "my-release"

**Version / Cluster**
- Which testkube version? 1.8.13

**Comment by ypoplavs** [comment]
Thank you for a request @f-helm. We will look into that shortly.

**Comment by ypoplavs** [comment]
@f-helm please try setting monitor labels using the following format and identation:
```
testkube-api:
  prometheus:
    enabled: true
    monitoringLabels:
      release: testkube
      label: prometheus
```
