### ISSUE TITLE
Testkube dashboard can't get the testkube api properly

### ISSUE THREAD

**Issue by mjrlgue** [kubeshop/helm-charts#428]
**Describe the bug**
The ingress not picking the correct url for testkube api when changing the default values

**To Reproduce**
1. Downloaded the `values.yml` from https://github.com/kubeshop/helm-charts/blob/main/charts/testkube/values.yaml
2. Updated and added the following fields:
```yml
testkube-api:
#...
  uiIngress:
    enabled: true
    className: "nginx"
    path: /results/(v\d/.*)
    hosts:
      - api.myhost.com
#..
testkube-dashboard:
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - testkube.myhost.com
  apiServerEndpoint: "api.myhost.com"
```
And upgrade the helm: `helm upgrade testkube  kubeshop/testkube -f .\values-prod.yml`
When I visit `testkube.myhost.com` I get the prompt to enter the testkube api url:
![image](https://user-images.githubusercontent.com/19733876/224387856-2775329c-d515-47a1-9b04-e926d5e8f23b.png)

**Expected behavior**
Expecting the configuration to work in first place without entering the api url in the prompt

**Version / Cluster**
- Which testkube version? 
Client Version 1.9.24
Server Version v1.9.32
- What Kubernetes cluster? openshift 
- What Kubernetes version?1.24.8
 
**Additional context**
But when I change `uiIngress.path` from `/results/(v\d/.*)` to the value `/`, it work!

Is the default configuration in `values.yml` correct? I'm trying to understand what's happening under the hood.

Thank you.

**Comment by juhosyrjanen** [comment]
Experiencing the same issue.  It seems that the api ingress path is `<url>/v1` and not the rregex that's referenced in defaults.

**Comment by xmj** [comment]
I can confirm that setting uiIngress.path to `/` and `apiServerEndpoint: "sub.host.tld"` (without `v1 / results/v1` or some such) is still required.

**Comment by devantler** [comment]
I made it work with the following values:

```yaml
  values:
    testkube-api:
      uiIngress:
        enabled: true
        hosts:
          - testkube.${cluster_domain}
        path: /v1 # This is required for the ingress to work per https://github.com/kubeshop/helm-charts/issues/428#issuecomment-1830163304
    testkube-dashboard:
      ingress:
        enabled: true
        hosts:
          - testkube.${cluster_domain}
      apiServerEndpoint: testkube.${cluster_domain}${cluster_ingress_port:=}
```

I am using flux post-build variables , so the `${}` are templated values that are replaced with real values during the kustomization build process.
