### ISSUE TITLE
testkube oauth2 proxy support for custom tls certs

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/helm-charts#447]
**Describe the enhancement you'd like to see**

As a Testkube operator
in order to use oauth2 proxy with a self-signed OIDC endpoint
I need testkube oauth2 helm chart to support mounting such custom certs through an extra volume + volume mount, similar to https://github.com/bitnami/charts/blob/4f55b58df012d9bbad764182a6f3c415b36b9767/bitnami/oauth2-proxy/values.yaml#L568-L571

**workaround**

Post process helm chart rendering, with flux my team uses the following to mount custom tls certs from host

```yaml
  postRenderers:
    # Mount host ssl certs to corpotate FQDN used
    - kustomize:
        patchesJson6902:
          - target:
              kind: Deployment
              name: oauth2-proxy
            patch:
              - op: add
                path: /spec/template/spec/volumes
                value: []
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: cert-volume
                  hostPath:
                    path: /etc/ssl/certs
                    type: Directory
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts
                value: []
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  mountPath: /etc/ssl/certs
                  name: cert-volume
```

**Additional context**
Add any other context, CLI input/output, etc. about the enhancement here.
