### ISSUE TITLE
HorizontalPodAutoscaler (HPA) resource does not work for newer kubernetes versions

### ISSUE THREAD

**Issue by zepeng811** [kubeshop/helm-charts#478]
**Describe the bug**
When attempting to apply the helm chart with the following configurations:
```
autoscaling:
    enabled: true
    minReplicas: ${apiserver_configs.min_replicas}
    maxReplicas: ${apiserver_configs.max_replicas}
    targetCPUUtilizationPercentage: ${apiserver_configs.target_cpu_utilization}
    targetCPU: ${apiserver_configs.target_cpu_utilization}
    targetMemoryUtilizationPercentage: ${apiserver_configs.target_memory_utilization}
```
for both `testkube-api` or `testkube-dashboard`, the apply will fail with the following error:
```
Error: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): unknown
field "targetAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource,
ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): missing required field "target" in
io.k8s.api.autoscaling.v2.ResourceMetricSource]
```

I'm running kubernetes version `1.23`, I believe the problem is kubernetes deprecated the apiVersion [autoscaling/v2beta1](https://github.com/kubeshop/helm-charts/blob/5d7fa00ab6ba5d631e4dd5c674e634dd31fb0f0a/charts/testkube-api/templates/hpa.yaml#L2) for HPA since `1.22`, and we need to use `autoscaling/v2` instead for newer versions with a slightly different syntax (see example PR in Additional Context section).

**To Reproduce**
1. Have a cluster with server version >= `1.23`
2. Turn autoscaling configuration on
3. install/upgrade helm with the autoscaling configuration
4. see the error

**Expected behavior**
The apply should succeed with the HPA resources created for any kubernetes server version

**Version / Cluster**
- Which testkube version? latest helm chart version `1.11.126`
- What Kubernetes cluster? `EKS`
- What Kubernetes version? `1.23`

**Additional Context**
Found an example PR with similar issue and fix: https://github.com/bitnami/charts/pull/10061/files
