### ISSUE TITLE
Pods with error status after deploying testkube with kustomize

### ISSUE THREAD

**Issue by f-helm** [kubeshop/helm-charts#522]
**Describe the bug**
After deploying helm chart with kustomize, multiple pods fail. This does not seem to impact functionality of testkube, but seem to be including tests which failing is irritating. This might not be limited to deploying with kustomize.

**To Reproduce**
1. Create yaml.file:
``` yaml
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: default

helmCharts:
- name: testkube
  namespace: default
  releaseName: testkube
  repo: https://kubeshop.github.io/helm-charts
  version: 1.11.220
```
2. In directory of yaml file, run `kustomize build --enable-helm . | kubectl apply -f -`
3. Multiple pods throw error:
- testkube-api-server-test-connection: `wget: can't connect to remote host (xx.xx.xxx.xx): Connection refused`
- testkube-operator-test-connection: `wget: bad address 'testkube-operator:80'`
- webhook-cert-patch: `Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work. Error: no secret with 'webhook-server-cert' in 'default' {"err":"secrets \"webhook-server-cert\" not found","level":"info","msg":"secret default/webhook-server-cert does not exist","source":"k8s/k8s.go:348","time":"2023-05-26T08:44:22Z"}`

**Expected behavior**
No failing pods on first install

**Version / Cluster**
- Which testkube version? 1.11.220
- What Kubernetes cluster? colima
- What Kubernetes version? v1.27.1+k3s1
