### ISSUE TITLE
Setting "allowTLS: true" fails the helm install

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/helm-charts#543]
**Describe the bug**
Using Amazon DocumentDB and setting allowTLS: true results in the following error

```
Helm install failed: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string Last Helm
```

**To Reproduce**
Set values 

```yaml

testkube-api:
  mongodb:
    dsn: "<dsn>"
    allowDiskUse: false
    dbType: docdb
    allowTLS: true
```

**Expected behavior**
The helm chart should install without any errors

**Version / Cluster**
- Which testkube version? 1.12.5
- Which Helm Chart version? 1.12.1
- What Kubernetes cluster? AWS EKS
- What Kubernetes version? 1.23

**Additional context**
The helm chart installs if `allowTLS` is not set. 

```
testkube-api:
  mongodb:
    dsn: "<dsn>"
    allowDiskUse: false
    dbType: docdb
```
