### ISSUE TITLE
Slack config causes template error

### ISSUE THREAD

**Issue by benfu-verses** [kubeshop/helm-charts#556]
**Describe the bug**
Defining `slackConfig` causes the testkube-api-server deployment to fail to deploy due to trying to parse the value of the config as base64.

**To Reproduce**

Set values file for testkube-api-server to:
```yaml
slackConfig:
    - ChannelID: ""
      selector: {}
      testName: []
      testSuiteName: []
      events:
        - "start-test"
        - "end-test-success"
        - "end-test-failed"
        - "end-test-aborted"
        - "end-test-timeout"
        - "start-testsuite"
        - "end-testsuite-success"
        - "end-testsuite-failed"
        - "end-testsuite-aborted"
        - "end-testsuite-timeout"
```

New TestKube api server fails to deploy with the following message:
```
Creating slack loader (error: error decoding slack config from base64: illegal base64 data at input byte 0)
```

**Expected behavior**
Setting `slackConfig` should override the value in the ConfigMap, but not be passed in as an environment variable value [here](https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube-api/templates/deployment.yaml#L102-L105).

**Version / Cluster**
- Helm chart version `1.11.206`

**Screenshots**
 
**Additional context**
[This snippet](https://github.com/kubeshop/testkube/blob/9a1a17288b4ade4f110e15aaad4850df440d4e5a/cmd/api-server/main.go#L533) indicates that if the env var is passed in, then it will be read as base64, but the Helm chart indicates that the `slackConfig` should be used only to template the ConfigMap, and thus the environment variable should be omitted completely or set as a different Helm value such as `slackConfigString`, where it takes in a base64 encoded string.

**Comment by davidB** [comment]
As `slackConfig` is injected via environment variable

```
            {{- if .Values.slackConfig }}
            - name: SLACK_CONFIG
              value:  "{{ .Values.slackConfig }}"
            {{- end }}
```

User, in `values.yaml` can not define it as yaml or raw json (also with the https://github.com/kubeshop/testkube/pull/4088 , because json include `"` that generate invalid yaml with the code above).

Maybe a backward compatible solution could be render `slackConfig` as a template like

```
            {{- if .Values.slackConfig }}
            - name: SLACK_CONFIG
              value:  {{ tpl .Values.slackConfig $ | quote}}
            {{- end }}
```

- existing base64(json) string continue to work
- inline json should be safely quoted (escaped), like

  ```
  slackConfig: >-
     [
       {
         "ChannelID": "xxxxx",
         "selector": {},
         "testName": [],
         "testSuiteName": [],
         "events": [
           "end-test-aborted",
           "end-test-failed",
           "end-test-timeout",
           "end-testsuite-aborted",
           "end-testsuite-failed",
           "end-testsuite-timeout"
         ]
       }
     ]
  ```
 
 - using function should be support (`fromJson`, `b64enc`,...) eg (not tested)
 
  ```
  slackConfigYaml:
    - ChannelID: C04E4BTE6KC # #wefox-ai-alerts
      selector: {}
      testName: [] # empty == all
      testSuiteName: [] # empty == all
      events:
        - start-test
        - end-test-aborted
        - end-test-failed
        - end-test-timeout
        - end-testsuite-aborted
        - end-testsuite-failed
        - end-testsuite-timeout
  slackConfig: {{ mustToJson $.Values.slackConfigYaml | b64enc }}
  ```
