### ISSUE TITLE
[testkube-dashboard] Overriding REACT_APP_ROOT_ROUTE when using a sub-path is unreliable

### ISSUE THREAD

**Issue by hobti01** [kubeshop/helm-charts#613]
**Describe the bug**
`REACT_APP_ROOT_ROUTE` is coded in the Helm Chart to use `.Values.ingress.path` and cannot be overridden with existing `extraEnvVars`.

When `.Values.ingress.path` contains a regex pattern (which is valid and necessary when using a sub-path), the `sed` parsing during startup of `testkube-dashboard` fails, causing a crashloop.
To avoid the crashloop, we have overridden `REACT_APP_ROOT_ROUTE` with `extraEnvVars`.  However, this creates duplicate variables during Helm templating.  Helm install works as expected but during Helm upgrade, the environment variable is not overridden to the `extraEnvVars` value and instead reverts to the value coded in the Chart with `.Values.ingress.path` and crashloop results.

**To Reproduce**
1. Set values.yaml
```yaml
testkube-dashboard:
  extraEnvVars:
    - name: REACT_APP_ROOT_ROUTE
      value: /mypath
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /mypath(/|$)(.*)
```
2. Run helm install
3. Run helm install --upgrade
4. See crashloop

**Expected behavior**

**Version / Cluster**
- Which testkube version? `1.13.34`
- What Kubernetes cluster? multiple
- What Kubernetes version? multiple

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**
```
W0814 22:43:44.480036    1644 warnings.go:70] spec.template.spec.containers[0].env[4].name: duplicate name "REACT_APP_ROOT_ROUTE"
```
