### ISSUE TITLE
Wrong placement of the CRDs in the operator chart

### ISSUE THREAD

**Issue by rajewluk** [kubeshop/helm-charts#627]
Testkube operator CRDs are placed in the templates folder of the operator helm chart. In consequence, when testkube fails and webhook service is not available the CRD and its CRs cannot be deleted. Basically, it makes Flux/ArgoCD tools work badly with testkube since they try to delete CRD when CRs are not deleted and that gets stuck if testkube services are already not available (as they get deleted in the random order along with other types of resources). To avoid it, CRDs should be placed in the cards folder of helm chart, as helm documentation states.

**Comment by vsukhin** [comment]
hey @rajewluk we started with this approach. it was a nice thing, but the prroblem was Helm didn't update CRD witj latest changes in this case. Might be, Helm was improved since that time, for @ypoplavs and @dejanzele t check

**Comment by rajewluk** [comment]
Understood, but the current approach makes the use of testkube in gitops approach very difficult and unreliable on upgrade.

**Comment by rajewluk** [comment]
Possibly, making them optional in the templates folder (flag in the values) and having them in the crds folder could help to solve it. First, they would get installed from crds folder, then would get updated from templates (if enabled, the helm app case). In ArgoCD the templates could be basically disabled as those from crds would get synced always by ArgoCD.

**Comment by vsukhin** [comment]
yes, let's review this issue again and see if we can do it better @ypoplavs

**Comment by devantler** [comment]
Any progress on this? This seems to still be the case when using Flux GitOps:

```txt
Helm install failed for release testkube/testkube with chart testkube@2.0.6: failed post-install: unable to build kubernetes object for deleting hook testkube/charts/testkube-api/templates/testworkflows/builtin-templates/distribute.yaml: resource mapping not found for name: "distribute--evenly" namespace: "" from "": no matches for kind "TestWorkflowTemplate" in version "testworkflows.testkube.io/v1"
ensure CRDs are installed first
```

**Comment by vsukhin** [comment]
hey, @devantler it should be realted to test workkflow template post hook installation, which should happen after CRD one. @tkonieczny and @emil2k can clarify

**Comment by devantler** [comment]
I am currently not setting any values for context:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: testkube
spec:
  interval: 1m
  chart:
    spec:
      chart: testkube
      version: 2.0.6
      sourceRef:
        kind: HelmRepository
        name: testkube
  # https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml
  values: {}
```
