### ISSUE TITLE
Ingress ClassName for helm chart 1.15.28

### ISSUE THREAD

**Issue by rr-jino-jose** [kubeshop/helm-charts#684]
**Describe the bug**
While using helm chart 1.15.28 I noticed for me nginx annotation `kubernetes.io/ingress.class` doesn't work. So I had to use it like this 

```
uiIngress:
    # -- Use Ingress
    enabled: true
    className: gopher-jino
    # -- Additional annotations for the Ingress resource.
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      #kubernetes.io/ingress.class: nginx
```

I don't see className parameter in helm chart. So may be we need to update it ?

**Expected behavior**
Attach an nginx ingress Class and create an LB

**Version / Cluster**
- Which testkube version? 
```
 kubectl testkube version                                                                                              4m 22s  ⎈ krupesh2/testkube 09:00:10 am

Client Version 1.15.20
Server Version 1.15.20
Commit 0f6ee4996613e46d86a23787811dc755d91377a2
Built by goreleaser
Build date 2023-11-21T07:52:09Z
```
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
EKS
- What Kubernetes version?
1.28
