### ISSUE TITLE
testkube-api-server pod keep print error log

### ISSUE THREAD

**Issue by TWpower** [kubeshop/helm-charts#712]
**Describe the bug**

testkube-api-server pod keep print below logs.

```
W0123 02:26:37.451359       1 reflector.go:458] pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: watch of *v1.TestSource ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"TestSource\" is registered for version \"tests.testkube.io/v1\" in scheme \"pkg/runtime/scheme.go:100\"") has prevented the request from succeeding
```

**To Reproduce**
1. Deploy helm chart
2. watch logs of testkube-api-server

**Expected behavior**
Just check it is ok for running testkube.

**Version / Cluster**
- Which testkube version?  
```
apiVersion: v2
dependencies:
- condition: testkube-operator.enabled
  name: testkube-operator
  repository: file://../testkube-operator
  version: 1.16.21
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.10.1
- condition: testkube-api.nats.enabled
  name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 0.19.1
- name: testkube-api
  repository: file://../testkube-api
  version: 1.16.23
- condition: testkube-dashboard.enabled
  name: testkube-dashboard
  repository: file://../testkube-dashboard
  version: 1.16.2
- name: global
  repository: file://../global
  version: 0.1.2
description: Testkube is an open-source platform that simplifies the deployment and
  management of automated testing infrastructure.
name: testkube
type: application
version: 1.16.29
```
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) GKE
- What Kubernetes version? 
```
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.6-gke.1700

```
