### ISSUE TITLE
Cannot load tests and testsuites after unintall and install helm without remove pvc

### ISSUE THREAD

**Issue by TWpower** [kubeshop/helm-charts#714]
**Describe the bug**
- Modify monogo db helm chart  value of ```persistence.resourcePolicy``` from "" to "keep" for keeping mongodb data
```
persistence:
  resourcePolicy: "keep"
```
- After uninstall helm chart and install helm  chart again, helm chart install is well done. However testkube cannot load tests and testsuites from mongodb even though test datas are exist in mongodb.
- However if I make new test with same pre exist test name, testkube dashboard find test.

**To Reproduce**
1. ```helm pull kubeshop/testkube```
2. after unzip tgz file
3. modify value of ```persistence.resourcePolicy``` from "" to "keep" in ```charts/mongodb/values.yaml```
4. ```helm install -n integration-test testkube .``` -> integration-test is our namespace
5. add some simple curl tests and testsuites using dashboard
6. ```helm uninstall -n integration-test testkube```
7. ```helm install -n integration-test testkube .```
8. open dashboard
9. Cannot find test and testsuites even though mongodb have tests
```
testkube> db.sequences.find()
[
  {
    _id: ObjectId('65b0efe2204041dd13ffaab1'),
    name: 'test',
    number: 4,
    istestsuite: false
  },
  {
    _id: ObjectId('65b0effc204041dd13ffaab8'),
    name: 'ts-testsuites',
    number: 1,
    istestsuite: true
  }
]
```
![Screenshot from 2024-01-24 20-18-15](https://github.com/kubeshop/helm-charts/assets/8542488/e7a6e8f5-526d-4f29-bd22-f81ea2e29014)

**Expected behavior**
- Tests and Testsuites are load well after install helm
- Just like to know is there anything that I missed or is it not support feature

**Version / Cluster**
- Which testkube version?  
```
apiVersion: v2
dependencies:
- condition: testkube-operator.enabled
  name: testkube-operator
  repository: file://../testkube-operator
  version: 1.16.21
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.10.1
- condition: testkube-api.nats.enabled
  name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 0.19.1
- name: testkube-api
  repository: file://../testkube-api
  version: 1.16.22
- condition: testkube-dashboard.enabled
  name: testkube-dashboard
  repository: file://../testkube-dashboard
  version: 1.16.2
- name: global
  repository: file://../global
  version: 0.1.2
description: Testkube is an open-source platform that simplifies the deployment and
  management of automated testing infrastructure.
name: testkube
type: application
version: 1.16.28
```
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) GKE
- What Kubernetes version? 
```
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.6-gke.1700
```

**Screenshots**
- test
![Screenshot from 2024-01-24 20-10-13](https://github.com/kubeshop/helm-charts/assets/8542488/eed3db8b-29ac-4e73-a2df-67ff1d8b0e0d)

- testsuites
![Screenshot from 2024-01-24 20-10-29](https://github.com/kubeshop/helm-charts/assets/8542488/1658cafb-4d0f-4b46-9216-b0146187cc28)

- cannot loaded
![Screenshot from 2024-01-24 20-18-15](https://github.com/kubeshop/helm-charts/assets/8542488/63b0aed9-3adb-4964-bd48-e24ef059971b)

**Additional context**
