### ISSUE TITLE
creating tests in different namespaces

### ISSUE THREAD

**Issue by KrawczowaKris** [kubeshop/helm-charts#715]
**Describe the enhancement you'd like to see**

Hello everyone,
I deployed testkube in ns `testkube`.
Now, if i create a test in the `testkube` ns, it is displayed in the testkube dashboard. But when i create a test in another ns it doesn't appear in the dashboard.
Is it possible to make tests created in another namespaces also appear in the testkube dashboard?

**Additional context**

**Comment by vsukhin** [comment]
hey @KrawczowaKris sure, yes. use our cloud solution @TheBrunoLopes @exu

**Comment by KrawczowaKris** [comment]
@vsukhin is multi-namespace supported in the self-hosted solution?
i tried using the following parameters:
```
testkube-api:
  additionalNamespaces:
    - prod
  multinamespace:
    enabled: true
```
