### ISSUE TITLE
Scheduling test does not work

### ISSUE THREAD

**Issue by TWpower** [kubeshop/helm-charts#727]
**Describe the bug**
- I schedule the test but it does not executed
- Is there any pod that I can investigate logs? There is nothing on api-server log
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: integration-test
  namespace: integration-test
  labels:
    executor: dip-integration-test-executor
    test-type: dip-integration-test-type
spec:
  type: dip-integration-test/type
  schedule: "48 9 * * *"
  executionRequest:
    variables:
      BASE_URI:
        name: BASE_URI
        value: "http://10.7.106.111/"
        type: basic
      BEARER_TOKEN:
        name: BEARER_TOKEN
        type: secret
        valueFrom:
          secretKeyRef:
            name: integration-test-testvars
            key: BEARER_TOKEN
    executePostRunScriptBeforeScraping: false
status:
  latestExecution:
    id: 65bb769c00ce0e6eb09db029
    number: 15
    startTime: 2024-02-01T10:46:52Z
    endTime: 2024-02-01T11:29:09Z
    status: passed

```

```
Name:                          integration-test-tests
Namespace:                     integration-test
Labels:                        executor=dip-integration-test-executor
                               test-type=dip-integration-test-type
                               testkube=tests
Annotations:                   <none>
Schedule:                      04 10 * * *
Concurrency Policy:            Forbid
Suspend:                       False
Successful Job History Limit:  3
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  <none>
  Containers:
   curlimage:
    Image:      curlimages/curl
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
    Args:
      curl -X POST -H "Content-Type: application/json" -d '{}' "http://testkube-api-server:8088/v1/tests/integration-test/executions"
    Environment:     <none>
    Mounts:          <none>
  Volumes:           <none>
Last Schedule Time:  <unset>
Active Jobs:         <none>
Events:              <none>

```

It works if I run cronjob manually
```
kubectl create job --from=cronjob/integration-test-tests manual-api-call -n integration-test
```

**To Reproduce**
1. Schedult test
2. Wait until test run

**Expected behavior**
- Test shoud be run when time meets

**Version / Cluster**
- Which testkube version? 
```
apiVersion: v2
dependencies:
- condition: testkube-operator.enabled
  name: testkube-operator
  repository: file://../testkube-operator
  version: 1.16.25
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.10.1
- condition: testkube-api.nats.enabled
  name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 0.19.1
- name: testkube-api
  repository: file://../testkube-api
  version: 1.16.25
- condition: testkube-dashboard.enabled
  name: testkube-dashboard
  repository: file://../testkube-dashboard
  version: 1.16.2
- condition: global.features.logsV2
  name: testkube-logs
  repository: file://../testkube-logs
  version: 0.2.0
- name: global
  repository: file://../global
  version: 0.1.2
description: Testkube is an open-source platform that simplifies the deployment and
  management of automated testing infrastructure.
name: testkube
type: application
version: 1.16.33
```
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) GKE
- What Kubernetes version?
```
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.6-gke.1700
```
