### ISSUE TITLE
Make the artifacts volume size configurable

### ISSUE THREAD

**Issue by lsoica** [kubeshop/helm-charts#737]
Currently the artifacts volume size is hardcoded to 1Gi https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube-api/pvc-template.yml.tmpl#L16

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Name }}-pvc
  namespace: {{ .Namespace }}
spec:
  storageClassName: {{ .ArtifactRequest.StorageClassName }}
  accessModes:
  {{- if .ArtifactRequest.SharedBetweenPods }}
    - ReadWriteMany
  {{- else }}
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: 1Gi
```
