### ISSUE TITLE
Allowing users to disable Liveness and Readiness Probe for mongodb chart

### ISSUE THREAD

**Issue by Eroyi** [kubeshop/helm-charts#831]
**Describe the enhancement you'd like to see**
Place an entry allowing users to disable or configure the Liveness and Readiness probe for the built-in MongoDB chart.

**Additional context**
The default configs for `livenessProbe` and `readinessProbe` are simply too frequent. MongoDB can consume up to 300m ~ 400m CPU usage. Once it's disabled, the MongoDB is back to 5m~10m usage, see the image below.
![image](https://github.com/kubeshop/helm-charts/assets/44765750/7eb217f6-fbc1-418d-888f-abaed484c54d)

Users can configure or disable probes in `values.yaml` by adding these entries. The following configure are tested in our environment:
```yaml
mongodb:
  # -- Toggle whether to install MongoDB
  enabled: true
  ······
  containerSecurityContext: {}
  # For OpenShift clusters use the following settings:
  #  runAsGroup: 1000670000
  readinessProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
```

I am aware that this chart is referenced from `bitmani/mongodb`, but given that testkube doesn't strictly follow bitmani's update, I thought it might be better to change it here.
