### ISSUE TITLE
Stable releases?

### ISSUE THREAD

**Issue by henrik-farre** [kubeshop/helm-charts#843]
**Describe the enhancement you'd like to see**
Current I'm trying to upgrade to a newer version of the helm chart, but I keep running into issues. Some of the versions can't install because of CRD issues, other times it is the testkube application that givens an error.

When I look at the releases for the helm chart I do not see any release notes that indicate I have to change anything or do something special to upgrade.

Currently I'm at helm chart 1.7.15 and have tried versions up until 1.7.48 (also clean installs).

Are all these versions development or pre-releases? 

I would very much like to see stable releases with changelogs ❤️

**Comment by devantler** [comment]
I am in the same boat as Henrik. 

This is our latest working release:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: testkube
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: testkube
      version: 1.17.20
      sourceRef:
        kind: HelmRepository
        name: testkube
  # https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml
  values:
    global:
      imageRegistry: ${testkube_image_registry:=docker.io}
```
