### ISSUE TITLE
Invalid manifest creation due to lack of guards around labels 

### ISSUE THREAD

**Issue by nabadger** [kubeshop/helm-charts#918]
**Describe the bug**
Using default values the helm template generates invalid manifests.

**To Reproduce**
```
helm template myapp . 
```

You will end up with something like:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myapp-operator-manager-role
  labels:
  namespace: default
...
```

This happens on multiple resources.

I think the bulk of the issues come from this file: https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-operator/templates/rolebinding.yaml#L8

It's also not clear where `globalLabels` comes from (not sure it's specified as an option in `values.yaml`)

**Expected behavior**
If there are no label values defined the `labels` field should not be present.

**Version / Cluster**
- Which testkube version? Chart version 2.0.17
